export { default as LogoBasic } from "./logo.png"
export { default as LogoFull } from "./logo-full.png"
export { default as LogoWhite } from "./logo-white.png"
export { default as BackgroundActivity } from "./background-activity.png"
export { default as AvatarDefault } from "./avatar-default.png"
