export enum PAGE {
    USER = "USER",
    CLASS = "CLASS",
    FACULTY = "FACULTY",
    ACTIVITY = "ACTIVITY",
    CATEGORY = "CATEGORY",
    PROOF = "PROOF",
    MY_ACTIVITIES = "MY_ACTIVITIES",
    MY_PROOFS = "MY_PROOFS"
}
