export enum SITE_MAP {
    INDEX = "/",
    SIGNIN = "/signin",
    ADMIN = "/admin",
    USERS = "users",
    CLASSES = "classes",
    FACULTIES = "faculties",
    STUDENTS = "students",
    ACTIVITIES = "activities",
    PROOFS = "proofs",
    CATEGORIES = "categories",
    ORGANIZATIONS = "organizations",
    ROLES = "roles",
    MY_FAVORITES = "my-favorites",
    MY_ACTIVITIES = "my-activities",
    MY_PROOFS = "my-proofs",
    MY_PROFILE = "/me",
    FORBIDDEN = "/403",
    NOT_FOUND = "*"
}
